import argparse
import asyncio
import json
import sys
from typing import Any, Dict, List, Optional

from app.nifi_client import _request, find_group_by_name, get_connections


def generate_html(group_name: str, processors: List[Dict], connections: List[Dict]) -> str:
    """Generate a premium HTML visualization of the NiFi flow."""
    
    # Build Mermaid graph content
    nodes = []
    for proc in processors:
        comp = proc.get("component", {})
        p_name = comp.get("name")
        p_id = comp.get("id")
        # Clean name for Mermaid compatibility
        safe_name = p_name.replace('"', "'")
        nodes.append(f'    P{p_id}["{safe_name}"]')

    edges = []
    for conn in connections:
        comp = conn.get("component", {})
        src_id = comp.get("source", {}).get("id")
        dest_id = comp.get("destination", {}).get("id")
        rels = ", ".join(comp.get("selectedRelationships", []))
        edges.append(f'    P{src_id} -- "{rels}" --> P{dest_id}')

    mermaid_content = "graph TD\n" + "\n".join(nodes) + "\n" + "\n".join(edges)

    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NiFi Flow Visualizer - {group_name}</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <style>
        :root {{
            --bg-color: #0f172a;
            --card-bg: #1e293b;
            --accent: #38bdf8;
            --text: #f8fafc;
        }}
        body {{
            font-family: 'Inter', system-ui, sans-serif;
            background-color: var(--bg-color);
            color: var(--text);
            margin: 0;
            padding: 2rem;
            display: flex;
            flex-direction: column;
            align-items: center;
        }}
        .container {{
            width: 100%;
            max-width: 1200px;
            background: var(--card-bg);
            padding: 2rem;
            border-radius: 1rem;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3);
            border: 1px solid rgba(255, 255, 255, 0.1);
        }}
        h1 {{
            margin-top: 0;
            font-weight: 800;
            background: linear-gradient(to right, #38bdf8, #818cf8);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            font-size: 2.5rem;
        }}
        .badge {{
            background: rgba(56, 189, 248, 0.1);
            color: var(--accent);
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            font-size: 0.875rem;
            font-weight: 500;
            border: 1px solid rgba(56, 189, 248, 0.2);
        }}
        .flow-container {{
            margin-top: 2rem;
            background: rgba(0, 0, 0, 0.2);
            padding: 2rem;
            border-radius: 0.75rem;
            overflow: auto;
        }}
        .mermaid {{
            visibility: hidden;
        }}
        .mermaid[data-processed="true"] {{
            visibility: visible;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>NiFi Flow Explorer</h1>
        <div style="display: flex; gap: 1rem; align-items: center;">
            <span class="badge">Group: {group_name}</span>
            <span style="color: #64748b;">Visualizing logically connected processors</span>
        </div>
        
        <div class="flow-container">
            <pre class="mermaid">
{mermaid_content}
            </pre>
        </div>
        
        <div style="margin-top: 2rem; color: #64748b; font-size: 0.875rem; text-align: center;">
            Generated by NiFi AI Agent • Live Metadata from Apache NiFi API
        </div>
    </div>

    <script>
        mermaid.initialize({{ 
            startOnLoad: true, 
            theme: 'dark',
            securityLevel: 'loose',
            flowchart: {{ 
                curve: 'basis',
                useMaxWidth: true,
                padding: 40
            }}
        }});
    </script>
</body>
</html>
"""


async def main() -> None:
    parser = argparse.ArgumentParser(description="Fetch and visualize NiFi process groups.")
    parser.add_argument("name", nargs="+", help="Name of the process group to fetch")
    parser.add_argument("--visual", action="store_true", help="Generate a flow_viz.html visualization file")
    args = parser.parse_args()
    
    name = " ".join(args.name)
    
    try:
        group = await find_group_by_name(name)
        if not group:
            print(f"Group '{name}' not found.")
            return

        group_id = group["id"]
        print(f"--- Group Details ---")
        print(f"Name: {name}")
        print(f"ID: {group_id}")
        
        # 1. Fetch Processors
        processors_data = await _request("GET", f"/process-groups/{group_id}/processors")
        processors_list = processors_data.get("processors", [])
        
        print(f"\n--- Processors inside the group ---")
        processor_map = {}
        for proc in processors_list:
            comp = proc.get("component", {})
            p_id = comp.get('id')
            p_name = comp.get('name')
            processor_map[p_id] = p_name
            print(f"[{p_name}] | ID: {p_id} | Type: {comp.get('type')}")

        # 2. Fetch Connections (The Flow)
        connections_data = await get_connections(group_id)
        connections_list = connections_data.get("connections", [])
        
        print(f"\n--- Flow Relationships (Connections) ---")
        for conn in connections_list:
            comp = conn.get("component", {})
            src = comp.get("source", {}).get("name")
            dest = comp.get("destination", {}).get("name")
            relationships = ", ".join(comp.get("selectedRelationships", []))
            print(f"[{src}]  --({relationships})-->  [{dest}]")
            
        # 3. Handle Visualization
        if args.visual:
            print("\nGenerating HTML visualization...")
            html_content = generate_html(name, processors_list, connections_list)
            with open("flow_viz.html", "w", encoding="utf-8") as f:
                f.write(html_content)
            print("Successfully created 'flow_viz.html'. You can open this file in your browser.")
        
    except Exception as exc:
        print("FAILED:", exc)
        sys.exit(1)

if __name__ == "__main__":
    asyncio.run(main())
